#! /bin/sh
cd ~/

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI
bspc monitor -eDi VII VIII IX

bspc config border_width         2
bspc config window_gap           8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Screenkey manage=off
bspc rule -a com-group_finity-mascot-Main manage=off
bspc rule -a firefoxdeveloperedition desktop="^2"
bspc rule -a LibreWolf desktop="^2"
bspc rule -a xpad desktop="^1" state=floating
bspc rule -a pomatez desktop="^1" state=floating

gsettings set org.gnome.desktop.interface gtk-theme Arc-Dark
gsettings set org.gnome.desktop.interface icon-theme Papirus-Dark
gsettings set org.gnome.desktop.interface font-name 'Cascadia Code 13'
gsettings set org.gnome.desktop.interface monospace-font-name 'Cascadia Mono 13'

# multiple keyboard layout
setxkbmap -layout us,np -option 'grp:alt_shift_toggle' &

feh --bg-scale $HOME/.config/windmill.jpg &
$HOME/.config/polybar/launch.sh &

killall -q dunst picom
dunst &
picom &

# redshift-gtk &
# mpd &
# /usr/lib/kdeconnectd &
# udiskie -s &

# Remap numpad 5 to d
xmodmap ~/.Xmodmap &
